// ─────────────────────────────────────────────────────────────────────────────
// ReportBuilder — formats ComplianceResult as a GitHub PR comment (Markdown)
// ─────────────────────────────────────────────────────────────────────────────

import { ComplianceResult, ACFinding } from './types';

const STATUS_EMOJI: Record<string, string> = {
  implemented: '✅',
  partial: '⚠️',
  missing: '❌',
  'cannot-verify': '❓',
};

const OVERALL_EMOJI: Record<string, string> = {
  pass: '✅',
  partial: '⚠️',
  fail: '❌',
  'cannot-verify': '❓',
};

const OVERALL_LABEL: Record<string, string> = {
  pass: 'All ACs Implemented',
  partial: 'Partially Implemented',
  fail: 'ACs Not Implemented',
  'cannot-verify': 'Cannot Verify from Code',
};

export function buildPRComment(result: ComplianceResult, prTitle: string, jiraBaseUrl: string): string {
  const { storyId, storyTitle, overallStatus, findings, summary } = result;

  const overallEmoji = OVERALL_EMOJI[overallStatus];
  const overallLabel = OVERALL_LABEL[overallStatus];

  const implementedCount = findings.filter(f => f.status === 'implemented').length;
  const partialCount = findings.filter(f => f.status === 'partial').length;
  const missingCount = findings.filter(f => f.status === 'missing').length;
  const cannotVerifyCount = findings.filter(f => f.status === 'cannot-verify').length;
  const total = findings.length;

  // Build the findings table
  const rows = findings.map(f => buildFindingRow(f)).join('\n');

  // Build the stat summary line
  const statParts: string[] = [];
  if (implementedCount > 0) statParts.push(`✅ ${implementedCount} implemented`);
  if (partialCount > 0) statParts.push(`⚠️ ${partialCount} partial`);
  if (missingCount > 0) statParts.push(`❌ ${missingCount} missing`);
  if (cannotVerifyCount > 0) statParts.push(`❓ ${cannotVerifyCount} cannot verify`);

  return `## ${overallEmoji} spec-proof — AC Compliance Report

| | |
|---|---|
| **Story** | [\`${storyId}\`](${jiraBaseUrl}/browse/${storyId}) — ${storyTitle} |
| **PR** | ${prTitle} |
| **Status** | ${overallEmoji} **${overallLabel}** |
| **Coverage** | ${statParts.join(' · ')} (${implementedCount}/${total} ACs) |

> ${summary}

---

### Acceptance Criteria Review

| | AC | Finding |
|---|---|---|
${rows}

---

<details>
<summary>📖 How to read this report</summary>

| Icon | Meaning |
|------|---------|
| ✅ Implemented | The AC is clearly visible in the PR diff |
| ⚠️ Partial | Some aspect is present but not fully covered |
| ❌ Missing | No evidence found in the code changes |
| ❓ Cannot Verify | The AC cannot be assessed from code alone (e.g. UX, timing, external system behavior) |

This report does **not** block merges by default. It is a signal for the author and reviewer — not a gate. Humans always decide.

</details>

<sub>🛡️ Generated by [story-proof-bot](https://github.com/amadalavamsi/story-proof-bot) · ${new Date().toUTCString()} · GPT-4o</sub>`;
}

function buildFindingRow(finding: ACFinding): string {
  const emoji = STATUS_EMOJI[finding.status] ?? '❓';

  // Add recommendation on a new line if present
  const recommendation = finding.recommendation
    ? `<br><sub>💡 ${finding.recommendation}</sub>`
    : '';

  return `| ${emoji} | **${finding.id}:** ${escapeMarkdown(finding.text)} | ${finding.evidence}${recommendation} |`;
}

function escapeMarkdown(text: string): string {
  // Escape pipe characters in table cells
  return text.replace(/\|/g, '\\|');
}
